/**
 * Created by Alex on 11/14/2017.
 */

// USERS
export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SAVE_USER_TOKEN = 'SAVE_USER_TOKEN';

export const SIGN_UP_STARTED = 'SIGN_UP_STARTED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

//PARKING SPOTS
export const ADD_PARKING_SPOT_STARTED = 'ADD_PARKING_SPOT_STARTED';
export const ADD_PARKING_SPOT_SUCCESS = 'ADD_PARKING_SPOT_SUCCESS';
export const ADD_PARKING_SPOT_FAIL = 'ADD_PARKING_SPOT_FAIL';
export const FETCHING_PARK_SPOTS_STARTED = 'FETCHING_PARK_SPOTS_STARTED'
export const FETCHING_PARK_SPOTS_SUCCESS = 'FETCHING_PARK_SPOTS_SUCCESS'
export const FETCHING_PARK_SPOTS_FAIL = 'FETCHING_PARK_SPOTS_FAIL'
export const FETCHING_PARK_SPOTS_SAVE = 'FETCHING_PARK_SPOTS_SAVE'
